# Generated by Django 4.1.5 on 2023-02-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterViewTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.CharField(choices=[('spring', 'Spring'), ('fall', 'Fall')], max_length=10)),
                ('is_open', models.BooleanField()),
                ('start_time', models.DateField()),
                ('document_deadline', models.DateField()),
                ('interview_start_time', models.DateField()),
                ('interview_end_time', models.DateField()),
                ('announce_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('student_id', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('introduce', models.TextField(default='')),
                ('motivate', models.TextField(default='')),
                ('to_do', models.TextField(default='')),
                ('etc', models.TextField(default='')),
                ('interview_requirement', models.TextField(default='')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.applicant')),
                ('interview_time_choice', models.ManyToManyField(related_name='interview_time', to='apply.interviewtime')),
            ],
        ),
    ]
