# Generated by Django 4.1.5 on 2023-02-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.CharField(choices=[('spring', 'Spring'), ('fall', 'Fall')], max_length=10)),
                ('start_time', models.DateField()),
                ('document_deadline', models.DateField()),
                ('announce_middle_time', models.DateTimeField()),
                ('interview_start_time', models.DateField()),
                ('interview_end_time', models.DateField()),
                ('announce_final_time', models.DateTimeField()),
                ('process', models.CharField(choices=[('close', 'Close'), ('apply', 'Apply'), ('middle', 'Middle'), ('final', 'Final')], default='close', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('introduce', models.TextField(default='')),
                ('motivate', models.TextField(default='')),
                ('to_do', models.TextField(default='')),
                ('etc', models.TextField(default='')),
                ('fixed_interview_time', models.DateTimeField(blank=True, null=True)),
                ('interview_requirement', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pass_document', models.BooleanField(default=True)),
                ('is_pass_final', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interview_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.interviewplace')),
                ('interview_time_choice', models.ManyToManyField(related_name='interview_time', to='apply.interviewtime')),
            ],
        ),
    ]
