# Generated by Django 4.1.5 on 2023-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='is_document_announe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='is_final_announce',
            field=models.BooleanField(default=False),
        ),
    ]
