# Generated by Django 4.1.5 on 2023-02-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_recruitment_is_document_announe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='fixed_interview_time',
            field=models.DateTimeField(null=True),
        ),
    ]
