# Generated by Django 4.1.5 on 2023-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_resume_created_at_resume_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_pass_document',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_pass_final',
            field=models.BooleanField(default=False),
        ),
    ]
