# Generated by Django 4.1.5 on 2023-02-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_resume_fixed_interview_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='fixed_interview_time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.interviewtime'),
        ),
    ]
