# Generated by Django 4.1.5 on 2023-02-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_resume_is_pass_document_resume_is_pass_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='is_document_announe',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='is_final_announce',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='is_open',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='process',
            field=models.CharField(choices=[('close', 'Close'), ('apply', 'Apply'), ('middle', 'Middle'), ('final', 'Final')], default='close', max_length=10),
        ),
    ]
