# Generated by Django 4.1.5 on 2023-02-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_alter_recruitment_announce_final_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='fixed_interview_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.interviewtime'),
        ),
    ]
