# Generated by Django 4.1.5 on 2023-02-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_alter_resume_fixed_interview_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='interview_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.interviewplace'),
        ),
    ]
