# Generated by Django 4.1.5 on 2023-02-17 07:56

import django.contrib.auth.models
from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
                ('object', user.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
